version: '3'

services:
  db:
    image: postgres:15
    # volumes:
    #   - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname ${DB_NAME} --username ${DB_USER}" ]
      interval: 1s
      timeout: 5s

  migrator:
    build: tern
    command:
      - migrate
      - --conn-string
      - postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      - --migrations
      - /migrations
    depends_on:
      db:
        condition: service_healthy

  server:
    build: .
    restart: always
    environment:
      DB_URL: postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      LOCAL: ${LOCAL}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - 8080:8080
    depends_on:
      - migrator

# volumes:
#   db_data:
