name: Go integration tests

on:
  pull_request:
    branches:
      - mkuptsov/main
  push:
    branches:
      - mkuptsov/main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Ensure go mod tidy has zero output
        run: go mod tidy -v && git diff --exit-code

      - name: Ensure gofumpt has zero output
        run: |
          go install mvdan.cc/gofumpt@latest
          gofumpt -l -w .
          git diff --exit-code
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true

      - name: Build project
        run: go build ./...

      - name: Integration tests
        run: go test -v ./integration_tests/...
